=== relense/DBM_Project/Projeto/src/metamodels/model.dtd
<!ELEMENT model (class+)>
        <!ATTLIST model
                name CDATA #REQUIRED>
<!ELEMENT class (attribute+, relation*)>
        <!ATTLIST class
                name CDATA #REQUIRED>
<!ELEMENT attribute (#PCDATA)>
        <!ATTLIST attribute
                name CDATA #REQUIRED
                type CDATA #REQUIRED
                required (true | false) "false">
<!ELEMENT relation EMPTY>
        <!ATTLIST relation
                name CDATA #REQUIRED
                type (1ToN | NToN | 1To1) "1To1">

=== relense/DBM_Project/Projeto/out/production/Projeto1.4/MyModels/BookStore/XML/bookstore.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE model SYSTEM "../metamodels/model.dtd">
<model name="BookStore">
    <class name="Author">
        <attribute name="first_name" type="String" />
        <attribute name="last_name" type="String" />
        <attribute name="email" type="String" />
    </class>
    <class name="Book">
        <attribute name="title" type="String" />
        <attribute name="pubDate" type="Date" />
        <attribute name="price" type="double" />
        <attribute name="quantity" type="int" />
        <relation name="author" type="1To1" />
    </class>
</model>

=== relense/DBM_Project/Projeto/out/production/Projeto1.4/models/person.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE model SYSTEM "../metamodels/model.dtd">
<model name="Person">
    <class name="Person">
        <attribute name="name" type="String" required="true" />
        <attribute name="age" type="int" required="true"/>
        <relation name="car" type="1ToN" />
    </class>
    <class name="Car">
        <attribute name="name" type="String" />
        <attribute name="year" type="int" />
        <attribute name="model" type="String" />
        <attribute name="brand" type="String" />
        <relation name="person" type="NToN" />
    </class>
</model>

=== relense/DBM_Project/Projeto/out/production/Projeto1.4/MyModels/Person/XML/person.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE model SYSTEM "../metamodels/model.dtd">
<model name="Person">
    <class name="Person">
        <attribute name="name" type="String" />
        <attribute name="age" type="int" />
    </class>
    <class name="Car">
        <attribute name="name" type="String" />
        <attribute name="year" type="int" />
        <attribute name="model" type="String" />
        <attribute name="brand" type="String" />
        <relation name="person" type="NToN" />
    </class>
</model>

=== relense/DBM_Project/Projeto/src/models/bookstore.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE model SYSTEM "../metamodels/model.dtd">
<model name="Bookstore">
    <class name="Author">
        <attribute name="first_name" type="String" required="true" />
        <attribute name="last_name" type="String" />
        <attribute name="email" type="String" />
        <relation name="book"  type="1To1"/>
        <relation name="cenas" type="1ToN"/>
    </class>
    <class name="Book">
        <attribute name="title" type="String" />
        <attribute name="pubDate" type="Date" />
        <attribute name="price" type="double" />
        <attribute name="quantity" type="int" />
        <relation name="author" type="NToN"/>
    </class>
    <class name="Cenas">
        <attribute name="name" type="String" />
        <attribute name="description" type="String" />
    </class>

</model>
